export default [
  { text: "HTML", icon: "icon-embed2" },
  { text: "CSS", icon: "icon-css3" },
  { text: "Sass", icon: "icon-sass" },
  { text: "JavaScript", icon: "icon-javascript" },
  { text: "Vue.js", icon: "icon-vue-dot-js" },
  { text: "Nuxt.js", icon: "icon-nuxt-dot-js" },
  { text: "ReactJS", icon: "icon-react" },
  { text: "Redux", icon: "icon-redux" },
  { text: "Next.js", icon: "icon-next-dot-js" },
  { text: "jQuery", icon: "icon-jquery" },
  { text: "Node.js", icon: "icon-node-dot-js" },
  { text: "Express.js", altIcon: "/images/express.svg" },
  { text: "Pugjs", altIcon: "/images/pugjs-icon.svg" },
  { text: "EJS", altIcon: "/images/ejs.svg" },
  { text: "Socket.io", altIcon: "/images/socketio-icon.svg" },
  { text: "Python", icon: "icon-python" },
  { text: "Flask", icon: "icon-flask" },
  { text: "PHP", icon: "icon-php" },
  { text: "MongoDB", icon: "icon-mongodb" },
  { text: "Firebase", icon: "icon-firebase" },
  { text: "MySQL", icon: "icon-mysql" },
  { text: "PostgreSQL", icon: "icon-postgresql" },
  { text: "AWS", icon: "icon-amazonaws" },
  { text: "Docker", icon: "icon-docker" },
];
